#!/bin/sh

export TERM=xterm-256color
export AR_DIR=~/.archive
export MANPAGER="vim -c '%s/_\|.\|\[[0-9]*m//e' -c 'set nonumber buftype=nofile filetype=man' -c 'goto' -"
export EDITOR=vim
export VISUAL=vim
export PAGER=less

alias vi=vim
alias view=vim
alias ls='ls -AFh --color=auto'
alias grep='grep --binary-files=without-match --color'
alias locate='locate --basename --existing'
alias screen="screen -DR"
alias cd="my_cd"

path_add () {
  # Extra paths
  # PATH_EXTRAS="/sbin:/usr/sbin:/usr/local/sbin:$HOME/bin:$HOME/.local/bin"
  path_extras="$1"
  paths=""
  for pth in $(echo $(echo "$PATH:$path_extras" | sed 's/:/\n/g')); do
      if [ -d $pth ]; then
          pth=$(realpath "$pth")
          echo ":${paths}:" | grep --quiet ":${pth}:" || {
              if [ -z "$paths" ]; then
                  paths="$pth";
              else
                  paths="${paths}:${pth}";
              fi
          }
      fi
  done

  export PATH="$PATHS";
}

path_add "/sbin:/usr/sbin:/usr/local/sbin:$HOME/bin:$HOME/.local/bin";

cd_ls() {
    "cd" "$@" && ls
}

my_cd() {
    le_path="$1"
    if test -f "$le_path"
    then
        le_path="$(dirname "$le_path")"
        echo "$le_path"
        cd_ls "$le_path"
        return
    fi
    cd_ls "$@"
}

purge() {
    target="${1:-.}"
    find "$target" -type f -mtime +7 -exec rm {} \;
    find "$target" -type d -empty -exec rmdir {} \;
}

local_config="$HOME/.shrc-local"
test -f "$local_config" && . "$local_config"
